### ISSUE TITLE
error on entering proxy

### ISSUE THREAD

**Issue by Behrouz-m** [nityanandagohain/proxy_configuration#9]
`Please run this program as Super user(sudo)

1:) Set Proxy
2:) Remove Proxy
3:) View Current Proxy
4:) Restore Default
5:) Exit

Choice (1/2/3/4/5) : 1
Enter proxy : xx.xxx.xxx.xx
Traceback (most recent call last):
  File "proxy.py", line 159, in <module>
    set_proxy(flag=0)
  File "proxy.py", line 106, in set_proxy
    proxy = input("Enter proxy : ")
  File "<string>", line 1
    xx.xx.xxx.xx
`

**Comment by GavinGaoYan** [comment]
sudo python3 proxy.py
